"""empty message

Revision ID: eb2020a86f28
Revises: b22a7c7e90b7
Create Date: 2019-09-24 08:07:54.636850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2020a86f28'
down_revision = 'b22a7c7e90b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviedetail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detail_id', sa.String(length=32), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('actor_img', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviedetail')
    # ### end Alembic commands ###
