"""empty message

Revision ID: fe57b8015890
Revises: eb2020a86f28
Create Date: 2019-09-24 10:23:37.136841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe57b8015890'
down_revision = 'eb2020a86f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moviedetail', sa.Column('actor_role', sa.String(length=100), nullable=False))
    op.add_column('moviedetail', sa.Column('comment_time', sa.String(length=32), nullable=False))
    op.add_column('moviedetail', sa.Column('comment_user', sa.String(length=32), nullable=False))
    op.add_column('moviedetail', sa.Column('director', sa.String(length=32), nullable=False))
    op.add_column('moviedetail', sa.Column('director_img', sa.String(length=100), nullable=False))
    op.add_column('moviedetail', sa.Column('title', sa.String(length=32), nullable=False))
    op.add_column('moviedetail', sa.Column('title_img', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moviedetail', 'title_img')
    op.drop_column('moviedetail', 'title')
    op.drop_column('moviedetail', 'director_img')
    op.drop_column('moviedetail', 'director')
    op.drop_column('moviedetail', 'comment_user')
    op.drop_column('moviedetail', 'comment_time')
    op.drop_column('moviedetail', 'actor_role')
    # ### end Alembic commands ###
